name = "Radio"
license = "GPLv3"
licenselink = "https://github.com/mehdy/hugo-radio/blob/master/LICENSE"
description = "Radio"
homepage = "https://github.com/mehdy/hugo-radio"
tags = ["radio", "podcast", "audio", "responsive"]
features = ["podcast", "audio"]
min_version = "0.41"

[author]
  name = "Mehdy Khoshnoody"
  homepage = "https://mehdy.me"
